sensor:
  - platform: scrape
    resource: https://yx.no/privat/drivstoffpriser
    name: 95 blyfri
    select: '#main > div > div > div > section.fuel-prices > ul > li:nth-child(1) > div:nth-child(2) > span.price-value'
    verify_ssl: false
  - platform: scrape
    resource: https://yx.no/privat/drivstoffpriser
    name: Diesel
    select: '#main > div > div > div > section.fuel-prices > ul > li:nth-child(2) > div:nth-child(2) > span.price-value'
    verify_ssl: false 
  - platform: scrape
    resource: https://yx.no/privat/drivstoffpriser
    name: 95 blyfri (sist oppdatert) 
    select: '#main > div > div > div > section.fuel-prices > ul > li:nth-child(1) > div:nth-child(1) > span'
    verify_ssl: false 
  - platform: scrape
    resource: https://yx.no/privat/drivstoffpriser
    name: Diesel (sist oppdatert) 
    select: '#main > div > div > div > section.fuel-prices > ul > li:nth-child(2) > div:nth-child(1) > span'
    verify_ssl: false 
